### Melihat Semua Catatan
GET http://localhost:3000/api/notes

### Menambah Catatan Baru
POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "judul": "Ngetest API.rest",
    "isi": "King Emyu menang coy"
}

### Mengedit Catatan (Ganti angka 1 dengan ID catatan yang ada)
PUT http://localhost:3000/api/notes/4
Content-Type: application/json

{
    "judul": "Ngetest edit",
    "isi": "King Emyu Ngalahin Liverpool"
}

### Menghapus Catatan (Ganti angka 1 dengan ID catatan)
DELETE http://localhost:3000/api/notes/5